### ISSUE TITLE
What g++ is required to build this

### ISSUE THREAD

**Issue by mulderp** [csguth/Liberty#2]
Hello,
this looks like an interesting library.
My apologies for asking a rather basic c++ question.
What is your build environment for this:
I've tried to build it with g++ 4.7, 5.3,,7.3 but I get build errors from the boost libraries (e.g. auto statement expects ")" ... )
Also, I tried MinGW on Windows.
A bit of help to get going would be great, e.g. what is the required g++ version?

Thanks a lot!

**Comment by mulderp** [comment]
got it working with g++ 7.3.0 and boost 1.62.0
also updated the Catch test librray location

**Comment by csguth** [comment]
Hi mulderp,

Sorry for the delay. It's a good thing you are able to build this.
